name: poke_radar_app
description: Web App Application for cards price trend - Flutter version

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  get: ^4.6.6
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^31.1.17
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^1.1.0
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
